services: 
  consumer:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_consumer
    env_file:
      - ../../.env
    restart: unless-stopped
    command: ["jobs/consumer.py"]
    networks:
      - kafka-net
    ports:
      - "4040:4040"

  silver:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_silver
    env_file:
      - ../../.env
    restart: unless-stopped
    command: ["jobs/silver_job.py"]
    networks:
      - kafka-net
    ports:
      - "4040:4040"
  
  gold:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_gold
    env_file:
      - ../../.env
    restart: "no"
    command: ["jobs/gold_job.py", "--date", "2013-08-23"]
    networks:
      - kafka-net
    ports:
      - "4040:4040"

networks:
  kafka-net:
    driver: bridge
