services: 
  consumer:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_consumer
    env_file:
      - ../../.env
    restart: unless-stopped
    # On lance le job consumer
    command: ["jobs/consumer.py"]
    networks:
      - kafka-net

  silver:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_silver
    env_file:
      - ../../.env
    restart: unless-stopped
    # On lance le job silver
    command: ["jobs/silver_job.py"]
    networks:
      - kafka-net
  
  gold:
    build:
      context: ../..
      dockerfile: infrastructure/docker/consumer.Dockerfile
    container_name: iot_spark_gold
    env_file:
      - ../../.env
    # IMPORTANT : processus batch, pas de restart en continu
    restart: "no"
    command: ["jobs/gold_job.py", "--date", "2013-08-23"]
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
